# Generated by Django 3.2.8 on 2021-10-12 13:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recognition', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserFaceCollection',
            new_name='FaceCollection',
        ),
    ]
