# Generated by Django 3.0.8 on 2021-11-15 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20211115_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='addedOnce',
        ),
        migrations.RemoveField(
            model_name='student',
            name='faceAdded',
        ),
        migrations.RemoveField(
            model_name='student',
            name='faceCount',
        ),
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
    ]
