# Generated by Django 3.0.8 on 2021-11-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_teachingassistant_dummy_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingassistant',
            name='unique_code',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
