# Generated by Django 3.0.8 on 2021-11-15 22:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_teachingassistant_unique_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingassistant',
            name='uni_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 15, 22, 35, 32, 867348)),
        ),
    ]
