# Generated by Django 3.2.8 on 2021-11-17 19:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20211118_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgotpassword',
            name='uni_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 17, 19, 36, 10, 192054, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='teachingassistant',
            name='uni_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 17, 19, 36, 10, 192054, tzinfo=utc)),
        ),
    ]
