# Generated by Django 3.0.8 on 2021-11-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_filepurposes_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filepurposes',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
