# Generated by Django 3.2.7 on 2021-09-22 20:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_staff_canaddusers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=datetime.datetime(2021, 9, 23, 1, 32, 9, 470924))),
                ('end_date', models.DateTimeField(default=datetime.datetime(2021, 9, 23, 1, 32, 9, 470924))),
                ('created_on', models.DateTimeField(default=datetime.datetime(2021, 9, 23, 1, 32, 9, 470924))),
                ('quizHeld', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 23, 1, 32, 9, 469931)),
        ),
        migrations.CreateModel(
            name='WrittenQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, null=True)),
                ('note', models.CharField(max_length=500, null=True)),
                ('max_time_limit_allowed', models.IntegerField(blank=True, default=600, null=True)),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faculty.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers_marked', django_mysql.models.ListTextField(models.CharField(default='', max_length=10000), size=100)),
                ('question_id', django_mysql.models.ListTextField(models.CharField(default='', max_length=100), size=100)),
                ('question_type', django_mysql.models.ListTextField(models.CharField(default='', max_length=10), size=100)),
                ('score', models.CharField(max_length=20, null=True)),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faculty.quiz')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faculty.course'),
        ),
        migrations.CreateModel(
            name='MCQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, null=True)),
                ('options', django_mysql.models.ListTextField(models.CharField(default='', max_length=1000), size=10)),
                ('correct_answers', django_mysql.models.ListTextField(models.IntegerField(default=0), size=10)),
                ('note', models.CharField(max_length=500, null=True)),
                ('max_time_limit_allowed', models.IntegerField(blank=True, default=600, null=True)),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faculty.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Enrolment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_on', models.DateTimeField(default=datetime.datetime(2021, 9, 23, 1, 32, 9, 470924))),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faculty.course')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('userType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.usertype')),
            ],
        ),
    ]
