# Generated by Django 3.2.7 on 2021-09-22 20:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_auto_20210923_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='hidden',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 23, 2, 10, 15, 811917)),
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='enrolled_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 23, 2, 10, 15, 812951)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 23, 2, 10, 15, 813946)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 23, 2, 10, 15, 813946)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 23, 2, 10, 15, 813946)),
        ),
    ]
