# Generated by Django 3.2.7 on 2021-09-25 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0006_auto_20210925_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq',
            name='markingScheme',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 25, 18, 59, 21, 700747)),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 25, 18, 59, 21, 690448)),
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='enrolled_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 25, 18, 59, 21, 692685)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 25, 18, 59, 21, 694683)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 25, 18, 59, 21, 694683)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 25, 18, 59, 21, 694683)),
        ),
    ]
