# Generated by Django 3.2.8 on 2021-10-06 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0011_auto_20211006_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 6, 14, 19, 48, 666500)),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 6, 14, 19, 48, 656087)),
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='enrolled_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 6, 14, 19, 48, 656087)),
        ),
        migrations.AlterField(
            model_name='partofsubmission',
            name='question_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='partofsubmission',
            name='question_type',
            field=models.IntegerField(default=2, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 6, 14, 19, 48, 656087)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 6, 14, 19, 48, 656087)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 6, 14, 19, 48, 656087)),
        ),
    ]
