# Generated by Django 3.2.8 on 2021-10-11 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0021_auto_20211011_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcq',
            name='mcqMarksGenerated',
        ),
        migrations.AddField(
            model_name='quiz',
            name='mcqMarksGenerated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 11, 23, 1, 52, 568106)),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 11, 23, 1, 52, 562077)),
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='enrolled_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 11, 23, 1, 52, 563079)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 11, 23, 1, 52, 564072)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 11, 23, 1, 52, 564072)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 11, 23, 1, 52, 564072)),
        ),
    ]
