# Generated by Django 3.2.8 on 2021-10-12 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0023_auto_20211011_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='writtenquestion',
            name='plagPercent',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='writtenquestion',
            name='sources',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 12, 21, 19, 25, 972078)),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 12, 21, 19, 25, 960964)),
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='enrolled_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 12, 21, 19, 25, 960964)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 12, 21, 19, 25, 960964)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 12, 21, 19, 25, 960964)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 12, 21, 19, 25, 960964)),
        ),
    ]
