# Generated by Django 3.2.8 on 2021-10-14 16:37

import datetime
from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0035_auto_20211014_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='partofsubmission',
            name='student_id',
            field=django_mysql.models.ListTextField(models.IntegerField(default=0), null=True, size=1000),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 14, 22, 7, 56, 179470)),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 14, 22, 7, 56, 173486)),
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='enrolled_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 14, 22, 7, 56, 174484)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 14, 22, 7, 56, 175481)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 14, 22, 7, 56, 175481)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 14, 22, 7, 56, 175481)),
        ),
    ]
