# Generated by Django 3.2.8 on 2021-10-14 16:45

import datetime
from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0036_auto_20211014_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='partofsubmission',
            name='percentage_match',
            field=django_mysql.models.ListTextField(models.IntegerField(default=0), null=True, size=1000),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 14, 22, 15, 12, 393808)),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 14, 22, 15, 12, 387350)),
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='enrolled_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 14, 22, 15, 12, 387350)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 14, 22, 15, 12, 388350)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 14, 22, 15, 12, 388350)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 14, 22, 15, 12, 388350)),
        ),
    ]
