# Generated by Django 3.2.8 on 2021-10-19 18:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0045_auto_20211019_0308'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesForActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='tab_change_images/')),
                ('typeAct', models.IntegerField(default=0, null=True)),
                ('timeStamp', models.DateTimeField(default=datetime.datetime(2021, 10, 19, 23, 37, 48, 778495))),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faculty.submission')),
            ],
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 19, 23, 37, 48, 778495)),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 19, 23, 37, 48, 762872)),
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='enrolled_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 19, 23, 37, 48, 762872)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 19, 23, 37, 48, 762872)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 19, 23, 37, 48, 762872)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 19, 23, 37, 48, 762872)),
        ),
        migrations.DeleteModel(
            name='TabChangeImages',
        ),
    ]
