# Generated by Django 3.2.8 on 2021-10-30 04:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0049_auto_20211021_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 30, 4, 9, 35, 125272)),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 30, 4, 9, 35, 117290)),
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='enrolled_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 30, 4, 9, 35, 118292)),
        ),
        migrations.AlterField(
            model_name='imagesforactivity',
            name='timeStamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 30, 4, 9, 35, 123278)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 30, 4, 9, 35, 119288)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 30, 4, 9, 35, 119288)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 30, 4, 9, 35, 119288)),
        ),
        migrations.CreateModel(
            name='TeachingAssistantPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isMainTA', models.BooleanField(default=False)),
                ('canManageTAPermissions', models.BooleanField(default=False)),
                ('canCheckAnswerSheets', models.BooleanField(default=True)),
                ('canAnnounce', models.BooleanField(default=True)),
                ('canCreateNewQuiz', models.BooleanField(default=False)),
                ('canManageQuiz', models.BooleanField(default=False)),
                ('enrolment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faculty.enrolment')),
            ],
        ),
    ]
