# Generated by Django 3.2.7 on 2021-09-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_faculty_staff_teachingassistant'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='canAddUsers',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
