# Generated by Django 3.2.8 on 2021-10-12 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20211011_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='faceAdded',
            field=models.BooleanField(default=False),
        ),
    ]
