# Generated by Django 3.2.8 on 2021-10-12 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_student_faceadded'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='faceCount',
            field=models.IntegerField(default=0),
        ),
    ]
