# Generated by Django 3.2.8 on 2021-10-13 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_student_facecount'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='addedOnce',
            field=models.BooleanField(default=False),
        ),
    ]
