# Generated by Django 3.0.8 on 2021-11-15 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20211115_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingassistant',
            name='dummy_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
