# Generated by Django 3.2.8 on 2021-11-18 00:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20211116_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgotpassword',
            name='uni_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 18, 0, 49, 39, 687588)),
        ),
        migrations.AlterField(
            model_name='teachingassistant',
            name='uni_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 18, 0, 49, 39, 687588)),
        ),
    ]
