# Generated by Django 3.2.8 on 2021-11-18 01:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20211118_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgotpassword',
            name='uni_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 17, 19, 48, 25, 264977, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='teachingassistant',
            name='uni_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 17, 19, 48, 25, 264977, tzinfo=utc)),
        ),
    ]
