# Generated by Django 3.2.8 on 2021-11-18 05:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20211118_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgotpassword',
            name='uni_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 18, 5, 35, 12, 862460, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='teachingassistant',
            name='uni_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 18, 5, 35, 12, 859663, tzinfo=utc)),
        ),
    ]
