# Generated by Django 3.2.8 on 2021-11-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_auto_20211115_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filepurposes',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
