# Generated by Django 3.2.8 on 2021-10-06 08:35

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0009_auto_20211005_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='answers_marked',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='question_id',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='question_type',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 6, 14, 5, 54, 117577)),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 6, 14, 5, 54, 117577)),
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='enrolled_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 6, 14, 5, 54, 117577)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 6, 14, 5, 54, 117577)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 6, 14, 5, 54, 117577)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 6, 14, 5, 54, 117577)),
        ),
        migrations.CreateModel(
            name='PartOfSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=500, null=True)),
                ('question_type', models.CharField(max_length=10, null=True)),
                ('answer', django_mysql.models.ListTextField(models.CharField(default='', max_length=10000), size=100)),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faculty.submission')),
            ],
        ),
    ]
