# Generated by Django 3.2.8 on 2021-10-14 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0037_auto_20211014_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='partofsubmission',
            name='maxPlagFromOtherStud',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 14, 22, 17, 24, 609538)),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 14, 22, 17, 24, 603551)),
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='enrolled_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 14, 22, 17, 24, 604553)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 14, 22, 17, 24, 604553)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 14, 22, 17, 24, 604553)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 14, 22, 17, 24, 604553)),
        ),
    ]
