# Generated by Django 3.0.8 on 2021-11-15 22:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0057_auto_20211115_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 15, 22, 17, 38, 580380)),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 15, 22, 17, 38, 572756)),
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='enrolled_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 15, 22, 17, 38, 573634)),
        ),
        migrations.AlterField(
            model_name='imagesforactivity',
            name='timeStamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 15, 22, 17, 38, 578734)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 15, 22, 17, 38, 574785)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 15, 22, 17, 38, 574767)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 15, 22, 17, 38, 574745)),
        ),
    ]
