# Generated by Django 3.2.8 on 2021-11-18 05:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0067_auto_20211118_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 18, 5, 38, 23, 486910, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 18, 5, 38, 23, 478928, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='enrolled_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 18, 5, 38, 23, 479931, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='imagesforactivity',
            name='timeStamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 18, 5, 38, 23, 485913, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='note',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='question',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='partofsubmission',
            name='answer',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 18, 5, 38, 23, 481924, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 18, 5, 38, 23, 481924, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 18, 5, 38, 23, 481924, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='writtenquestion',
            name='note',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='writtenquestion',
            name='question',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
